### ISSUE TITLE
Issue Loading Certain Files

### ISSUE THREAD

**Issue by FelixGP** [Darayavaush/decensooru#1]
The following posts don't show up for me, although their icons are displayed in the search results.
http://danbooru.donmai.us/posts/2907335
http://danbooru.donmai.us/posts/2907994
http://danbooru.donmai.us/posts/2906774
http://danbooru.donmai.us/posts/2906054
Not sure if this issues is restricted to me, but I thought I'd point it out. I went four pages back but after the first two pages no other images seemed to have this issue.

**Comment by Darayavaush** [comment]
All four work for me. I can't really see how what you described can happen due to this script - both thumbnails and full images pull their info from the same source, so I'm tempted to assume that something unrelated to this script broke. Is there still a problem now, several hours later?

**Comment by FelixGP** [comment]
Seems the issue was resolved after updating the database.
