### ISSUE TITLE
new preview upload moved to a new server

### ISSUE THREAD

**Issue by ghost** [Darayavaush/decensooru#10]
they've done it again ...
any way here's an example of how the new one looks like.
https://raikou4.donmai.us/preview/fb/4a/fb4acff791ca2fa41b1be7da2e495828.jpg
this seems to be effecting only new uploads.

**Comment by Darayavaush** [comment]
I think I'll wait for a few days before touching this. Danbooru has been schizophrenic (well, more so than usual) since the start of this month with all the domain switches and just random page errors, so I wouldn't be surprised in the least if they change this crap back.

**Comment by ghost** [comment]
hopefully they wont make it worse
