### ISSUE TITLE
This script doesn't work, period.

### ISSUE THREAD

**Issue by andy6915** [Darayavaush/decensooru#11]
I have edited the BBB script perfectly as nstructed, tried the latest version of both this and BBB. I have tried it with Pale Moon and Firefox. I've tried that other version that is supposed to do it for you, after this version failed.

https://github.com/friendlyanon/decensooru

End result after 2 hours of this nonsense? A script that does nothing and everything is still hidden.

**Comment by andy6915** [comment]
https://snag.gy/AEs1jS.jpg

https://snag.gy/EIedlM.jpg

Highlighted the section I am supposed to edit, look over it. Should be no issues, as I said. So what is the problem here?

**Comment by Darayavaush** [comment]
Let's stick to Pale Moon for debugging.

1. Did you get a "downloading full batch" box in the top right?
2. Does BBB by itself work both before and after the patch (technically the patch shouldn't affect the core functionality, but just in case)? You should have a new menu item "BBB Settings" on the top bar of links.
3. If yes, did you select the "placeholder" options in settings?
4. Look into the console (F12 - console). Does it say anything Decensooru-related there?
5. On Firefox, which version did you install, gm4 or the normal one?
