### ISSUE TITLE
Firefox 68.0.1 not show text right corner

### ISSUE THREAD

**Issue by aeri** [Darayavaush/decensooru#13]
With the latest version of Firefox, installed and modified BBB, the right corner is empty and not show any message. The picture not show but the message of the gold account is not shown.

**Comment by Darayavaush** [comment]
Can't reproduce. Anything in the console?

**Comment by aeri** [comment]
I use GreaseMonkey latest version and uBlock Origin, the console of the script or browser?

**Comment by Darayavaush** [comment]
Er, I'm not sure what you mean by "console of the script", so let's just say both.

**Comment by aeri** [comment]
Tested in a virtual machine with a new Firefox installation and it seems that works good, appears the first time a message that shows a loading batch, after Done, some post are available.

It seems that i have a plugin that causes incompatibility with decensooru.
