### ISSUE TITLE
Some posts can only view thumbnails.

### ISSUE THREAD

**Issue by grapefruit25** [Darayavaush/decensooru#15]
Don't know if it a bug or not.
Some posts  " The artist requested removal of this page " or " You need a gold account to see this image. " can only see the thumbnails, but click in with no picture.
And " This post was deleted for the following reasons:Unapproved in three days " this kind of posts will
show the picture correctly.
Is this a bug? Thanks.

**Comment by tallos** [comment]
danbooru made some changes which seem to have broken BBB's ability to fetch/modify posts and images a couple hours ago. i suspect it was these changes:
> Certain selectors on the posts page have changed:
> #image-container is now .image-container.
> #note-container is now .note-container.
> #image-resize-link is now .image-view-original-link.
> The HTML structure of notes has changed.

**Comment by Darayavaush** [comment]
Urghhh whyyy. What is the point of those changes aghh

Welp, thankfully at least it didn't take me too much BBB-poking to find a fix. Give the updated readme a read.

**Comment by nonamethanks** [comment]
It was changed so that now notes are automatically resized with the image.

**Comment by Darayavaush** [comment]
I don't really see what turning IDs into classes has to do with that.

**Comment by nonamethanks** [comment]
Well the relevant commits are https://github.com/danbooru/danbooru/commit/1126147deebe722bc8a413cf1e093b2b448eceba, https://github.com/danbooru/danbooru/commit/87a51129b8ffe9a12037657c5afd26b4870d121a and another number of commits made in the last month, which changed a lot of the notes javascript to make it more dynamic.

**Comment by tallos** [comment]
i am still getting the bbb error after replacing line 1631

**Comment by Darayavaush** [comment]
Define "BBB error".

**Comment by tallos** [comment]
popup warnign at the top:
BBB: Post content could not be located.

post i use for testing, thumbnail works correctly via decensooru, no image appears when the post is opened
https://danbooru.donmai.us/posts/3517090
image of post and error:
https://imgur.com/ATp9UYy

**Comment by Darayavaush** [comment]
Ah, I didn't fully update the instructions, my bad. Should be fixed now.

**Comment by tallos** [comment]
i think its trying to work but decensooru cleared its DB and i dont see the "force refresh of decensooru" link anywhere

**Comment by Darayavaush** [comment]
Assuming you have the latest version of the script, it should be in the footer, next to "Keyboard shortcuts".

**Comment by tallos** [comment]
not showing up for me.
it is running at least according to f12 though, its just stuck on 1 DB entry and there is nothing next to keyboard shortcuts
il post again in a couple hours or days if it still hasnt updated the DB

**Comment by Darayavaush** [comment]
Check the source of your decensooru.user.js, make sure it matches the latest version on Github. Specifically, there should be a line `$('#page-footer').append('– <a id="decensooruForceFullRefresh">Force full refresh of Decensooru</a>');`

**Comment by tallos** [comment]
reinstalling decensooru fixed it
my only remaining problems are entirely BBB problems unrelated to decensooru. (image swap, resize post etc not working)
thank you for the fixes and troubleshooting.

**Comment by grapefruit25** [comment]
I have replaced 2 line in BBB, but it still doesn't work.
Still the "BBB: Post content could not be located." things.
I'm using the firefox 74.0, these is no `$('#page-footer').append('– <a id="decensooruForceFullRefresh">Force full refresh of Decensooru</a>');` in my decensooru_gm4.user.js.
Is that why?

**Comment by Darayavaush** [comment]
Just tested the GM4 version on Firefox and it worked just fine. Reinstall BBB and re-edit it; tell me if it still doesn't work after that.

**Comment by grapefruit25** [comment]
It works. Thank you very much.

**Comment by grapefruit25** [comment]
I just found that the "view original" button is gone.
https://i.imgur.com/j7AhHSy.png
And it will appear if I reinstall BBB with unedited version.
Can you fix this ? thanks.
BTW some option in BBB also doesn't work like Alternate Image Swap ,
but I don't know if it's BBB or dencensooru problem, cause unedited version also doesn't work.

**Comment by Darayavaush** [comment]
There is no "view original", because all images will always be displayed as originals, even if non-decensooru'd images are set to be shown as samples. 

> I don't know if it's BBB or dencensooru problem, cause unedited version also doesn't work.

If the unedited version of BBB doesn't work, how exactly can it be caused by Decensooru? :-/ (yes, it is caused by BBB, since it hasn't been updated after the Danbooru update)

**Comment by grapefruit25** [comment]
With unedited and setting "Default image width" on danbooru site, "view original" will appear.

**Comment by Kano709** [comment]
Images were fixed but notes are still gone after following main page instructions, is there any way to get them back?

**Comment by Darayavaush** [comment]
Notes work fine for me, and there is no code either in Decensooru or the changed BBB sections that has anything to do with them, so I'm not sure what could have happened. Do notes work on non-golden-account posts? What's your browser and Greasemonkey type (original GM, Tampermonkey, etc.)?

**Comment by Kano709** [comment]
For me notes only work on gold account images, bizarrely enough. 
Firefox54 developer edition/tampermonkey. 
Tried a fresh install for both scripts and followed instructions on main page but still can only see notes on gold images. I can see notes on non-gold images if I disable BBB.

**Comment by Darayavaush** [comment]
Well, that's a problem with BBB. However, since its maintainers seem to have departed this world and I had an edited script anyway, I decided to just upload it directly (even though this fix doesn't have anything to do with Decensooru). Install the file I just added.

**Comment by Kano709** [comment]
Whatever the issue was, that fixed it. Thanks.
