### ISSUE TITLE
"The fucking assholes broke us once again"

### ISSUE THREAD

**Issue by pilltwilliams** [Darayavaush/decensooru#16]
I'm sorry chief, but this time I don't see a way to reverse their shenanigans.
Still, allow me to provide you with something from my imagination. While I'm no programmer, I hope this helps in some way.

>They hide the image id itself
>But still returns the matched images in the search
>That means it IS returning some kind of string - to identify paywalled content.
>one string per id, randomized for each search? This might rape the search engine, however.
>one single hash, generated at search, that obfuscates all ids of that search?
>If either one is done server-side, it's uncrackable. Might as well make another search engine.
>However, if JS fuckery is involved, it might be possible to crack or bypass it.

Anyway, like I said, I see no way to reverse it.
Oh, but the thing still works if you already know the image ID - like when you use iqdb and the like. That I appreciate and thank you for.

Hope you find manage to find a way!

**Comment by Darayavaush** [comment]
Thank you for your support, but those ideas are garbage. ¯\_(ツ)_/¯

**Comment by impman** [comment]
It returns the source URL if there is one however, so I've just been clicking that since it broke.

**Comment by Hakkin** [comment]
Using the fields currently returned from the API, unique posts can still be identified.
Creating a map of something like `hash(created_at, uploader_id, image_width, image_height, file_size) -> md5` should work the same as the previous `id -> md5` map.
There doesn't seem to be any collisions between these fields in the whole danbooru dataset, let alone the limited banned dataset, and they should remain constant for all posts.
That being said, it might be a moot point since the developer has already stated on the forum that any attempt to bypass the limitation will just result in the complete removal of the results from the API.

**Comment by Darayavaush** [comment]
> That being said, it might be a moot point since the developer has already stated on the forum that any attempt to bypass the limitation will just result in the complete removal of the results from the API.

Holy shit what. Can I have a source for this? I searched around on the forum, but didn't find anything.

Re multi-field map: that's an interesting idea, but I was (and still am) thinking of something quite different.

**Comment by Hakkin** [comment]
> Holy shit what. Can I have a source for this? I searched around on the forum, but didn't find anything.

https://danbooru.donmai.us/forum_posts/169548
https://danbooru.donmai.us/forum_posts/169759

**Comment by Darayavaush** [comment]
Welllllllll fuck. Thank you for bringing this to my attention, this indeed changes the situation significantly.

(ngl though, I'm seriously tempted to just do the minimal possible working update anyway just to see those raging imbeciles damage their own site)

**Comment by Darayavaush** [comment]
Welp, we done here.
Fs in chat.

**Comment by Revemohl** [comment]
Rest in peace, you will be sorely missed. And a great fuck you to whoever was that person responsible for ratting BBB out and breaking it in first place, which caused Decensooru to come to life (and now end).
Here's hoping that Gelbooru, Sankaku and whatever else continue being better than Danbooru for as long as possible, and that more and more people catch on to Danbooru's awfulness as time passes so they too move on to the alternatives.
