### ISSUE TITLE
Script never pulls update batches

### ISSUE THREAD

**Issue by BadRoad** [Darayavaush/decensooru#3]
Using BBB v8.0.2 I've tried inserting the code as instructed using both Greasemonkey and Tampermonkey.  I never get the popup and browser slowdown for pulling update batches, and hidden thumbnails remain hidden.
I'm using Firefox 57.0.4 64-bit on Windows 7, if that matters.

**Comment by Darayavaush** [comment]
Did you install decensooru.user.js itself? That's the part responsible for the popup and batch pulling.

**Comment by BadRoad** [comment]
Well, now I have.  I got the popup, but it didn't freeze for anywhere near thirty seconds and I still don't see any hidden posts, just the placeholders.

**Comment by Darayavaush** [comment]
Ah, I see. There were changes in some Greasemonkey syntax in its last version. I'll make a fix ASAP.

**Comment by Darayavaush** [comment]
Try [this](https://github.com/Darayavaush/decensooru/blob/master/decensooru_gm4.user.js) (or, alternatively, switch to Violentmonkey, since it has better backwards compatibility and is generally better put together). If it doesn't work, please post console contents (F12).

**Comment by BadRoad** [comment]
It works on ViolentMonkey.  Thanks.

**Comment by Darayavaush** [comment]
You're welcome. ;)
