### ISSUE TITLE
Crash when pulling full batch.

### ISSUE THREAD

**Issue by ghost** [Darayavaush/decensooru#4]
Using Waterfox 56.0.4.1 x64 with Violentmonkey.

It seems that either my measly 4gb of RAM is not enough for decensooru, or it memory leaks.

When trying to pull a full batch it eats up all of the RAM plus the pagefile, and not only the browser freezes, the whole system freezes due to the pagefile getting filled up.

If I let it run it, eventually after 5-10 minutes it finishes and pulls the full batch. But the browser remains unstable, and when I close it, it crashes and apparently the batch is lost. When i open the browser again all the thumbnails and images appear hidden.

Is this a bug? if not, Is there a way to download and store the full batch manually?

**Comment by Darayavaush** [comment]
Can't reproduce. I installed Waterfox 56.0.4.1 with VM in a VM (heh) with 4 GB of RAM and monitored RAM and CPU usage. Full batch pulling took me around 2-3 minutes, during which time it gradually ate up around 1.5 GB of RAM and moved between 25% and 100% CPU usage (I also got a "page unresponsive" warning). Thereafter both RAM and CPU usage went back down to norm with no side effects afterwards.

1. Take a look at the console (F12). What does it say?
2. Did you modify the BBB source as specified in the instructions?
3. If console says `Decensooru started. There are 66957 items in DB.  Nothing to do, wait for next batch.` and you modified the source, try again on a clean profile.

**Comment by ghost** [comment]
I tried a new profile and Waterfox still ate my RAM and pagefile, but it no longer crashes. Takes about 4-5 minutes to pull the full batch and the browser and system become unresponsive during this time. I guess that upgrading to a T9600 helped a bit.

Console after batch, danbooru main page:

JQMIGRATE: Migrate is installed with logging active, version 1.4.1  application-aac730656b1a20f2e4bf2d4ec8d3b714ab7bf70732d7d3625968dd54091e0590.js:4:10616
Decensooru started. There are 1 items in DB.  danbooru.donmai.us:15:5

Console, after searching for "loli".

JQMIGRATE: Migrate is installed with logging active, version 1.4.1  application-aac730656b1a20f2e4bf2d4ec8d3b714ab7bf70732d7d3625968dd54091e0590.js:4:10616
Decensooru started. There are 68042 items in DB.  posts:15:5
Nothing to do, wait for next batch.  posts:18:9

Also, how do I force the script to pull a full batch?

**Comment by ghost** [comment]
Additional info: While the clean profile works, the old profile persists with this problem.

Disabled all complements but ViolentMonkey

The process keeps eating CPU resources but stays at 50%. When I close waterfox, the process still keeps running with 50% CPU usage, but after some minutes it crashes. crash report shows something about xul.dll

Will reinstall Waterfox, migrate my stuff to a clean profile and report back.

**Comment by ghost** [comment]
Reinstalled and migrated everything. It still eats RAM and processing power, but it no longer crashes. So it must be a problem with the system itself. Guess it's about time I retired this craptop from 2008.

**Comment by Darayavaush** [comment]
Do you mean it eats RAM and CPU while fetching the batch (which is expected) or after the batch is pulled and you restart (which is not expected)?
