### ISSUE TITLE
A lot of images won't load after Danbooru made some changes 

### ISSUE THREAD

**Issue by bluefiberbread** [Darayavaush/decensooru#5]
http://danbooru.donmai.us/posts/1250771
http://danbooru.donmai.us/posts/1584115
http://danbooru.donmai.us/posts/1700814
http://danbooru.donmai.us/posts/1424520
http://danbooru.donmai.us/posts/1025240

https://danbooru.donmai.us/forum_posts/143612

**Comment by Darayavaush** [comment]
I've noticed this myself, they seem to be gradually restoring the images that give a 404 (I'm trawling through recent posts and a few days ago I was getting a 404 on 60% of them, today I didn't get it on any). Just wait and the problem should fix itself (#﻿3 in your list is already fixed), this is not a Decensooru issue.
