### ISSUE TITLE
Pulling full batch on every page load.

### ISSUE THREAD

**Issue by BadRoad** [Darayavaush/decensooru#6]
Exactly what it sounds like.  Every time I load a page on Danbooru, it spends about thirty seconds pulling a full batch.  Even if I just refresh the page I'm on.  Might have something to do with a recent Firefox update?

**Comment by Darayavaush** [comment]
Which Decensooru version (standard or GM4) are you using, on which monkey (Grease, Violent or Tamper) and on which FF version?

**Comment by Darayavaush** [comment]
Well, I can't do much if you aren't even going to tell me on which configuration the problem occurs.
