### ISSUE TITLE
Thumbnails dont work

### ISSUE THREAD

**Issue by ghost** [Darayavaush/decensooru#7]
thumbnails for HIDDEN images do not work but the images them selves do load when i open it in a new tab
https://i.imgur.com/x9EVK0g.png
https://i.imgur.com/z0ikaeK.png
and some images do not load like this one 
https://danbooru.donmai.us/posts/3197220

**Comment by Darayavaush** [comment]
Are you sure you followed all installation instructions precisely? The first piece of code for insertion into BBB is responsible for displaying the thumbnails, so messing it up would result in the exact symptoms you're seeing.

The last image is too new, retry tomorrow.

**Comment by ghost** [comment]
Thanks for your help! everything's fixed now.
https://drive.google.com/open?id=16Uh_J0ATQcgDaGA-cxxJ8j7mBqSwIu3T
i'll leave a link for the edited B3 V8.3 for anyone who wants to use it.

**Comment by Darayavaush** [comment]
Glad to be of help. ;)

Not exactly the best place for putting this link, since I doubt people will be checking closed issues before the first installation. I don't want to put it into the repo either, since then I'll have to keep track of BBB's updates, which I don't want to bother with.

**Comment by ghost** [comment]
understandable
